openapi: 3.0.0
info:
  title: Subscription hub API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Локальный сервер

security:
  - BearerAuth: []
  - TenantID: []

paths:

  /auth/signup:
    $ref: './paths/auth.yaml#/signup'
  /auth/signin:
    $ref: './paths/auth.yaml#/signin'

  /profile:
    $ref: './paths/profile.yaml#/profile'
  /profile/full:
    $ref: './paths/profile.yaml#/full'

components:
  securitySchemes:

    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT токен пользователя"

    TenantID:
      type: apiKey
      in: header
      name: X-Tenant-ID
      description: "Идентификатор компании для выполнения операций в её контексте"